name: CI with Automated Testing

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Flask for testing
        run: pip install flask

      - name: Run Unit Tests
        run: python test_app.py

      - name: Build Docker Image
        # This step only runs if the 'Run Unit Tests' step passes!
        run: docker build -t python-cicd-app .
	- name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python-cicd-app:latest'
          format: 'table'
          exit-code: '1' # This will fail the build if it finds "CRITICAL" bugs
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'